version: '3.8'

services:
  app:
    build: .
    container_name: listas-compartidas
    restart: unless-stopped
    ports:
      - "3000:80"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

volumes:
  app-data:
    driver: local
